---
title: "ASSOCIAÇÃO BRASILEIRA DE JURIMETRIA (ABJ) <br/> ESTATUTO SOCIAL"
output: 
    bookdown::html_document2: 
      number_sections: no
---

```{r echo=FALSE}
art <- 1
```

# Capitulo I - DENOMINAÇÃO, NATUREZA, SEDE E OBJETIVOS. 

**Art. `r (art<-art+1)`°**. A Associação Brasileira de Jurimetria, neste estatuto designada simplesmente pela sigla ABJ, fundada em 21 de março de 2011, com sede e foro nesta capital do Estado de São Paulo, na Rua XXX, é uma associação civil sem fins lucrativos, sujeito de direito privado, regida pelo presente estatuto e demais disposições legais que lhe forem aplicáveis.

**Art. `r (art<-art+1)`°**. A ABJ tem como finalidade:

I) Incentivar e divulgar a jurimetria, a aplicação da estatística no estudo de fenômenos jurídicos, aos seus associados e ao público em geral.

I) Incentivar a utilização do método científico na elaboração e avaliação de políticas públicas.

I) Realizar, promover e participar de cursos, palestras, seminários, conferências, _workshops_, congressos e qualquer forma de reunião que objetive a difusão da jurimetria.

I) Estimular e promover a produção, a publicação e a circulação de artigos, boletins e livros que debatam ou façam o uso da jurimetria.

I) Promover a criação, organização e disponibilização de bases de dados jurídicos.

I) Promover a cooperação e intercâmbio entre estatísticos e operadores do direito.

I) Promover a defesa de interesses ou direitos difusos, coletivos, transindividuais, relacionados aos demais objetivos listados neste artigo.

**Parágrafo único**. Para cumprir suas finalidades sociais, a ABJ se organizará em tantas unidades quantas se fizerem necessárias, em todo o território nacional, as quais funcionarão mediante delegação expressa da matriz e se regerão pelas disposições contidas neste estatuto.

# Capítulo II - DO QUADRO SOCIAL.

**Art. `r (art<-art+1)`°**. O número de associados é ilimitado.

**Art. `r (art<-art+1)`°**. Os associados não respondem subsidiariamente pelas obrigações da ABJ.

**Art. `r (art<-art+1)`°**. Os associados gozam de direitos iguais no âmbito da ABJ.

**Art. `r (art<-art+1)`°**. São direitos dos associados, desde que em dia com seus deveres estatutários:

I) Receber comunicações sobre as atividades da ABJ.
I) Votar e ser votado para qualquer cargo da Diretoria.
I) Recorrer à Assembleia Geral contra qualquer ato da Diretoria.
I) Solicitar o seu desligamento da ABJ a qualquer tempo, mediante carta protocolada na sede da Associação, desde que não esteja em débito com suas obrigações associativas.

**Parágrafo único**. Não haverá distribuição de lucros ou resultados aos associados.

**Art. `r (art<-art+1)`°**. São deveres dos associados:

I) Cumprir e fazer cumprir o presente estatuto, as decisões da Assembleia Geral e da Diretoria.
I) Zelar pelo nome e patrimônio da ABJ.
I) Honrar pontualmente com as contribuições associativas da ABJ.

**Art. `r (art<-art+1)`°**. A admissão de novos associados dependerá de aprovação da Diretoria.

**Art. `r (art<-art+1)`°**. A Diretoria deverá considerar as solicitações das pessoas interessadas em se tornarem associados e dar ciência de sua decisão aos solicitantes.

**Art. `r (art<-art+1)`**. Se a Diretoria recusar a proposta de filiação, o candidato poderá apresentar nova solicitação após o período mínimo de 6 (seis) meses.

**Art. `r (art<-art+1)`**. Os associados poderão ser excluídos do quadro social por justa causa, por meio de deliberação da maioria simples da Diretoria.

**Art. `r (art<-art+1)`**. Os associados pagarão anuidades à ABJ no valor e condições fixadas pela Diretoria.

# Capítulo III - DA ASSEMBLEIA GERAL, DO CONSELHO CIENTÍFICO, DO LABORATÓRIO DE JURIMETRIA E DA DIRETORIA.

**Art. `r (art<-art+1)`**. São órgãos sa ABJ:

I) a Assembleia Geral;
I) o Conselho Científico;
I) o Laboratório de Jurimetria; e
I) a Diretoria.

<!-- Assembleia -->

**Art. `r (art<-art+1)`**. Não se admite o voto por procuração nas reuniões dos órgãos da ABJ.

**Art. `r (art<-art+1)`**. A Assembleia Geral é a instância máxima de deliberação da ABJ e será constituída pelos seus associados em pleno gozo de seus direitos, sendo soberana em suas decisões, respeitadas as disposições deste estatuto, tendo as seguintes prerrogativas.

I) Fiscalizar os membros da ABJ na consecução de seus trabalhos.
I) Eleger e destituir os administradores.
I) Deliberar sobre a previsão orçamentária e a prestação de contas.
I) Estabelecer o valor das mensalidades dos associados.
I) Deliberar quanto à compra e venda de imóveis da ABJ.
I) Aprovar o regimento interno, que disciplinará vários setores de atividades da ABJ.
I) Alterar, no todo ou em parte, o presente estatuto.
I) Deliberar quanto à dissolução da ABJ.
I) Decidir, em última instância, sobre todo e qualquer assunto de interesse social, bem como sobre os casos omissos no presente estatuto.

**§ 1°**. A Assembleia Geral será instalada, em primeira convocação, com a presença de, no mínimo, mais da metade dos associados quites. Em segunda convocação, a Assembleia será instalada com qualquer número de associados quites. São válidas as deliberações aprovadas pela maioria dos associados quites presentes à Assembleia.

**§ 2°**. As convocações dos associados para as reuniões da Assembleia Geral serão feitas por meio do envio de mensagem por correio eletrônico e aviso disponibilizado no "site" da ABJ e poderão ser feitas por 1/5 dos associados.

**Art. `r (art<-art+1)`**. A Assembleia Geral Ordinária realizar-se-á uma vez por ano, para votar a prestação de contas da Diretoria e demais assuntos constantes da pauta.

<!-- Conselho Científico -->

**Art. `r (art<-art+1)`**. O Conselho Científico da ABJ compõe-se de no mínimo 3 (três) e no máximo 11 (onze) Conselheiros.

**§ 1°**. A nomeação dos Conselheiros dar-se-á pela Diretoria, em reunião convocada especialmente para esse fim.

**§ 2°**. O Diretor-Presidente terá assento permanente no Conselho Científico, sem direito a voto, ressalvado o caso de empate.

**§ 3°**. O mandato dos Conselheiros é de 3 (três) anos, permitida a recondução. O mandato se estenderá até a eleição de posse de cada novo Conselheiro.

**Art. `r (art<-art+1)`**. Compete ao Conselho Científico:

I) Orientar academicamente os eventos e pesquisas executados pela ABJ.
I) Respeitar e fazer cumprir o presente estatuto.
I) Opinar sobre matérias de sua competência que a Diretoria lhe submeter.

**Art. `r (art<-art+1)`**. As reuniões do Conselho Científico serão presididas pelo Conselheiro-presidente, nomeado pela Diretoria, para um mandato de 3 (três) anos, ou por quem este expressamente indicar, em caso de usa ausência.

**Parágrafo único**. As deliberações do Conselho Científico serão tomadas pela maioria simples dos Conselheiros presentes à reunião, com quórum de instalação e deliberação mínimo de 3 (três) Conselheiros.

**Art. `r (art<-art+1)`**. As reuniões do Conselho Científico serão convocadas pelo Conselheiro-presidente ou pelo Diretor Executivo da ABJ.

<!-- Laboratório de jurimetria -->

**Art. `r (art<-art+1)`**. O Laboratório de Jurimetria compõe-se de no mínimo 3 (três) e no máximo 10 (dez) membros.

**§ 1°**. A nomeação dos membros dar-se-á pela Diretoria, em reunião convocada especialmente para esse fim.

**§ 2°**. O mandato dos membros é de 3 (três) anos, permitida a recondução. O mandato se estenderá até a eleição de posse de cada novo membro.

**Art. `r (art<-art+1)`**. Compete ao Laboratório de Jurimetria:

I) Coordenar, planejar e executar as pesquisas da ABJ.
I) Informar a Diretoria a respeito das questões técnicas relativas aos projetos, convênios e parcerias da ABJ.
I) Manter atualizada a Diretoria a respeito de avanços tecnológicos surgidos na academia e no mercado, úteis aos objetivos da ABJ.
I) Respeitar e fazer cumprir o presente estatuto.

**Art. `r (art<-art+1)`**. As reuniões do Laboratório de Jurimetria serão presididas por seu coordenador, nomeado pela Diretoria, para um mandato de 3 (três) anos, ou por quem este expressamente indicar, em caso de usa ausência.

**Parágrafo único**. As deliberações do Laboratório de Jurimetria serão tomadas pela maioria simples dos membros presentes à reunião, com quórum de instalação e deliberação mínimo de 3 (três) membros.

<!-- Diretoria -->

**Art. `r (art<-art+1)`**. A Diretoria da ABJ compõe-se de um Diretor Executivo, um Diretor Financeiro e um Diretor Social eleitos pela Assembleia Geral.

**§ 1°**. O mandato da Diretoria é de 3 (três) anos, permitida a recondução. O mandato se estenderá até a eleição e posse dos novos Diretores.

**§ 2°**. As deliberações da Diretoria serão tomadas pela maioria simples dos Diretores presentes à reunião, com quórum de instalação e deliberação mínimo de 3 (três) Diretores.

**Art. `r (art<-art+1)`**. Compete à Diretoria:

I) Respeitar e fazer cumprir o presente estatuto.
I) Cumprir com os objetivos da ABJ.
I) Executar as deliberações da Assembleia Geral.
I) Deliberar sobre admissão e exclusão de associados.
I) Submeter à Assembleia Geral, anualmente, a prestação de contas.
I) Fixar o valor de anuidades e taxas, se for o caso.
I) Nomear ou dissolver comissões e grupos de trabalho.
I) Aprovar o orçamento anual da ABJ.
I) Escolher os membros do Conselho Científico.
I) Aprovar os projetos de pesquisa nos quais a ABJ tomará parte.
I) Aprovar propostas a serem apresentadas em concorrências públicas ou privadas.
I) Aprovar convênios e parcerias da ABJ com outras entidades, públicas ou privadas.

**Art. `r (art<-art+1)`**. Compete ao Diretor Executivo:

I) Expedir comunicações e ofícios em nome da Diretoria para os demais órgãos da ABJ e entidades externas, públicas ou privadas.
I) Convocar e presidir as reuniões da Diretoria e as Assembleias Gerais.
I) Assinar os cheques, contratos e demais documentos obrigacionais da ABJ, juntamente com o Diretor Financeiro.
I) Comparecer às reuniões do Conselho Científico.
I) Orientar as atividades do Laboratório de Jurimetria.
I) Indicar um membro da Diretoria para substituí-lo em caso de impossibilidade ou impedimento.
I) Proferir voto de qualidade, no caso de empate nas deliberações do Conselho Científico ou da Diretoria.

**Parágrafo único**. Por meio de procuração, o Diretor Executivo poderá delegar ao Diretor Financeiro a atribuição de isoladamente abrir conta bancária, assinar os cheques e ordens de pagamento da ABJ.

**Art. `r (art<-art+1)`**. Compete ao Diretor Financeiro:

I) Administrar o patrimônio e as finanças da ABJ.
I) Gerenciar os projetos da ABJ, juntamente com o Coordenador do Laboratório de Jurimetria.
I) Supervisionar a escrituração contábil.
I) Elaborar a proposta de previsão orçamentária anual.
I) Providenciar a elaboração dos balanços da ABJ.
I) Organizar a cobrança de contribuiçõs dos associados.
I) Assinar cheques, contratos e demais documentos obrigacionais da ABJ, juntamente com o Diretor Executivo.

**Art. `r (art<-art+1)`**. Compete ao Diretor Social:

I) Representar a ABJ em juízo e fora dele.
I) Promover a divulgação dos eventos e ações da ABJ.
I) Identificar oportunidades de colaboração da ABJ com outras entidades, públicas e privadas.
I) Orientar politicamente os projetos e pesquisas executados pela ABJ.

**Art. `r (art<-art+1)`**. As reuniões da Diretoria serão convocadas pelo Diretor Executivo da ABJ.

<!-- Diretoria e Conselho Científico -->

**Art. `r (art<-art+1)`**. Os mandatos dos membros da Diretoria, do Laboratório de Jurimetria e do Conselho Científico só poderão ser interrompidos por renúncia ou por decisão da maioria absoluta dos associados quites, em Assembleia Geral.

# Capítulo IV - DO PATRIMÔNIO.

**Art. `r (art<-art+1)`**. O patrimônio da ABJ será formado pelas contribuições previstas neste estatuto e nos regimentos, inscrições em eventos, bem como por doações ou legados e demais bens por ela adiquiridos.

# Capítulo V - DA EXTINÇÃO.

**Art. `r (art<-art+1)`**. A ABJ terá duração por prazo indeterminado, podendo ser extinta a qualquer tempo, por deliberação de seus associados, em Assembleia Geral especialmente convocada para este fim, por meio de aviso epistolar remetido com dois meses de antecedência.

**Parágrafo único**. Os associados deliberarão a destinação do patrimônio da ABJ.

# Capítulo VI - DA MODIFICAÇÃO DESTE ESTATUTO.

**Art. `r (art<-art+1)`**. O presente estatuto poderá ser modificado, no todo ou em parte, a qualquer tempo, por deliberação aprovada pela maioria simples dos associados quites, presentes em Assembleia Geral especialmente convocada para este fim.

# Capítulo VI - DAS DISPOSIÇÕES GERAIS.

**Art. `r (art<-art+1)`**. O foro para dirimir quaisquer pendências ou controvérsias da ABJ será o da Comarca da Capital de São Paulo, renunciando-se a qualquer outra por mais privilegiada que seja.

**Art. `r (art<-art+1)`**. Os casos omissos neste estatuto serão discutidos pela Diretoria.

São Paulo, 02 de Janeiro de 2017.

Diretor Executivo







